### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by Mr-3rd** [Mr-3rd/MCTC_ITEC2905_fall2023_proj3_team03_Justin_Amy_Peng#36]
Create the official requirements.txt document that houses all of the specific version numbers of all packages installed for this project

Use: `pip freeze > all_packages.txt`

to make a file with every package installed

**Comment by pengxuemoua** [comment]
Will close issue once we are done building app.

**Comment by pengxuemoua** [comment]
Unable to install unittest

![image](https://github.com/Mr-3rd/MCTC_ITEC2905_fall2023_proj3_team03_Justin_Amy_Peng/assets/121327389/976a0f5a-63c7-4f9b-bd77-76d6484543b4)

**Comment by pengxuemoua** [comment]
#43, #58

closing issue
