### ISSUE TITLE
Update README.md with application details

### ISSUE THREAD

**Issue by Mr-3rd** [Mr-3rd/MCTC_ITEC2905_fall2023_proj3_team03_Justin_Amy_Peng#5]
Refer to this article that discusses what makes a good ReadMe.

https://www.geeksforgeeks.org/what-is-readme-md-file/

**Comment by Mr-3rd** [comment]
@pengxuemoua  & @amylynndee  Here is a great example of a clear Readme. Note the elements from the article above clear and concise, our goal is something similar, let me know how I can help!

https://github.com/claraj/cat_flask/blob/master/README.md

**Comment by pengxuemoua** [comment]
@Mr-3rd, okay for me to resolve issue?

**Comment by Mr-3rd** [comment]
> @Mr-3rd, okay for me to resolve issue?

I would say yes
