### ISSUE TITLE
Expedited Change - Website Crash 

### ISSUE THREAD

**Issue by pengxuemoua** [Mr-3rd/MCTC_ITEC2905_fall2023_proj3_team03_Justin_Amy_Peng#59]
Expedited Change, users affected due to website crash. Executive approval was granted to quickly merge into main.

@Mr-3rd, can you document your code here please?

**Comment by Mr-3rd** [comment]
added an if statement to main branch car_recalls.htlm filed to handle saving cars without recalls

**Comment by Mr-3rd** [comment]
https://github.com/Mr-3rd/MCTC_ITEC2905_fall2023_proj3_team03_Justin_Amy_Peng/commit/9d5cdaac486abdb16a558d792a540e0a48ff5387

**Comment by Mr-3rd** [comment]
branch that was updated

**Comment by Mr-3rd** [comment]
@pengxuemoua  approve and close at your convenience

**Comment by pengxuemoua** [comment]
@Mr-3rd Thank you for the detailed comments! Issue has been resolved and customers are happy. Closing issue.
