### ISSUE TITLE
Update Main page

### ISSUE THREAD

**Issue by pengxuemoua** [Mr-3rd/MCTC_ITEC2905_fall2023_proj3_team03_Justin_Amy_Peng#9]
After reviewing the main page, we should modulate the main branch to store the Database, APIs, and flask templates.

@Mr-3rd , Please create a folder sub structure to modulate the deployment.

**Comment by Mr-3rd** [comment]
Utilizing this as reference: https://github.com/claraj/cat_flask/tree/master/apis

**Comment by Mr-3rd** [comment]
@pengxuemoua  & @amylynndee  arranged this updated in Saturday Eve meeting, closing with this commit:

https://github.com/Mr-3rd/MCTC_ITEC2905_fall2023_proj3_team03_Justin_Amy_Peng/commit/99bb0eda517b08e0fd3718a69b91ac27de4e0c1f
